### ISSUE TITLE
Require Answer

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MTVHousing#6]
If user has not already filed an Answer

1. Introduce a need for answer 
2. move answer questions to beginning of interview and inform user they need to have already filed an answer in their case or build an answer - kickout and
2. Link to [MADE](https://interviews.gbls.org/interview?i=docassemble.MAEvictionDefense%3Adata%2Fquestions%2Feviction.yml#page1)
3.  Provide screen for user to upload Answer to Motion to Vacate
4. if user does has neither already filed nor uploaded Answer, user gets kicked out.

From Gordon in conversation with Caroline - unrecorded and [Management Meeting 9/1/2020 19 minutes in](https://youtu.be/xfWMIbe4Dt4?list=PLy6i9GFGw5GzcPqGyZQ06lPp35v6S5-YF&t=1158).

**Comment by mikecronin7** [comment]
talked to Gordon, the answer is not required and we dont think that we should make it required to finish the interview. Just need to strongly encourage the user to file an answer. Gordon made a good suggestion about adding instruction to file an answer and why its important on the cover letter.

**Comment by mikecronin7** [comment]
Should also find a different place to put the series of questions about the answer.

I was thinking more towards the end of the interview

**Comment by mikecronin7** [comment]
Include language of strongly encouraging that the person files an answer.
No kickout screen, quinten agrees that we should allow them to finish the interview if they have not finished it.

**Comment by mikecronin7** [comment]
This issue has been spliced into various issues, including stronger language in issue #14 and editing the template in issue #17 and including an upload screen issue.
